import Link from "next/link";
import { PageHeader } from "@/components/AppShell";
import { formatDuration, summarizeServices } from "@/lib/analytics";
import { correlateIncident } from "@/lib/incident-correlation";
import { readTelemetry } from "@/lib/telemetry";
export const dynamic="force-dynamic";
export default async function CorrelationPage(){
 const records=await readTelemetry(500),services=summarizeServices(records),primary=services.find(s=>s.status!=="Healthy")??services[0],finding=correlateIncident(records,primary);
 const failed=records.filter(r=>r.signal_type==="trace"&&((r.status_code??0)>=500||r.severity?.toUpperCase()==="ERROR")),kube=records.filter(r=>r.signal_type==="k8s_event"),displayScore=finding?Math.min(finding.score,95):0;
 return <><PageHeader eyebrow="CORRELATION ENGINE" title="Incident correlation" description="Understand the failure from user symptom to suspected cause.">{finding&&<span className={`pill ${finding.confidence==="High"?"critical":finding.confidence==="Medium"?"warning":"info"}`}>{finding.confidence} confidence · {displayScore}%</span>}</PageHeader>
 {finding&&primary?<>
 <article className="panel cluster-overview"><div className="panel-title"><div><h2>Working diagnosis</h2><p>Evidence-backed hypothesis · responder confirmation required</p></div></div><h1 style={{fontSize:"24px"}}>{finding.summary}</h1><p style={{marginTop:"12px",maxWidth:"1100px",fontSize:"15px",lineHeight:1.7}}>{finding.diagnosis}</p></article>
 <div className="metrics"><article><span>Impacted service</span><strong>{finding.affectedService}</strong><small>{finding.primarySymptom}</small></article><article><span>Failure domain</span><strong style={{fontSize:"18px"}}>{finding.failureDomain}</strong><small>{finding.failureMode}</small></article><article><span>Suspected cause</span><strong>{finding.dependency??"Unknown"}</strong><small>{finding.infrastructureState}</small></article><article><span>Blast radius</span><strong>{finding.blastRadius}</strong><small>currently observed impact</small></article><article><span>Confidence</span><strong>{displayScore}%</strong><small>{finding.confidence} · unconfirmed</small></article></div>
 <article className="panel" style={{marginBottom:"18px"}}><div className="panel-title"><div><h2>Failure mental model</h2><p>Follow the causal chain instead of isolated telemetry</p></div></div><div className="cluster-facts" style={{gridTemplateColumns:"repeat(4,1fr)"}}><div><span>1 · USER IMPACT</span><strong>{finding.affectedService}</strong><small style={{display:"block",marginTop:"7px"}}>{finding.primarySymptom}<br/>{finding.secondarySymptom}</small></div><div><span>2 · FAILED REQUEST PATH</span><strong>{finding.requestPath.join(" → ")}</strong><small style={{display:"block",marginTop:"7px"}}>failed traces isolate this path</small></div><div><span>3 · FAILURE DOMAIN</span><strong>{finding.dependency??finding.workload??"Not isolated"}</strong><small style={{display:"block",marginTop:"7px"}}>{finding.infrastructureState}</small></div><div><span>4 · WORKING CONCLUSION</span><strong>{finding.failureMode}</strong><small style={{display:"block",marginTop:"7px"}}>hypothesis · {displayScore}% confidence</small></div></div></article>
 <div className="split"><article className="panel"><div className="panel-title"><div><h2>Evidence chain</h2><p>How SignalDeck moved from symptom to suspected cause</p></div></div><div className="list">{finding.evidenceSteps.map((s,i)=><div className="list-item" key={`${s.label}-${i}`}><div style={{width:"100%"}}><div style={{display:"flex",justifyContent:"space-between",gap:"12px",alignItems:"center"}}><strong>{i+1}. {s.label}</strong><span className="pill info" style={{fontSize:"10px"}}>{s.source}</span></div><p style={{marginTop:"7px"}}>{s.detail}</p>{s.meta&&<small style={{display:"block",marginTop:"5px"}}>{s.meta}</small>}</div></div>)}</div></article>
 <article className="panel"><div className="panel-title"><div><h2>Failure classification</h2><p>The operational model SignalDeck currently believes best fits</p></div></div><div className="list"><div className="list-item"><div><strong>Failure domain</strong><p>{finding.failureDomain}</p></div></div><div className="list-item"><div><strong>Failure mode</strong><p>{finding.failureMode}</p></div></div><div className="list-item"><div><strong>Infrastructure state</strong><p>{finding.infrastructureState}</p></div></div><div className="list-item"><div><strong>Primary symptom</strong><p>{finding.primarySymptom}</p></div></div><div className="list-item"><div><strong>Secondary symptom</strong><p>{finding.secondarySymptom}</p></div></div></div></article></div>
 <article className="panel" style={{marginTop:"18px"}}><div className="panel-title"><div><h2>Why not something else?</h2><p>Competing hypotheses ranked against the evidence we actually have</p></div></div><div className="cluster-facts" style={{gridTemplateColumns:`repeat(${finding.alternatives.length},1fr)`}}>{finding.alternatives.map(a=><div key={a.label}><span className={`pill ${a.likelihood==="Strong"?"critical":a.likelihood==="Possible"?"warning":"info"}`}>{a.likelihood}</span><strong style={{display:"block",marginTop:"12px"}}>{a.label}</strong>{a.reasons.map((r,i)=><small key={i} style={{display:"block",marginTop:"7px"}}>• {r}</small>)}</div>)}</div></article>
 <div className="split" style={{marginTop:"18px"}}><article className="panel"><div className="panel-title"><div><h2>Evidence coverage</h2><p>Independent signals supporting the hypothesis</p></div><strong>{finding.coverage.filter(x=>x.present).length}/{finding.coverage.length}</strong></div><div className="cluster-facts" style={{gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))"}}>{finding.coverage.map(x=><div key={x.label}><span>{x.present?"✓ ":"○ "}{x.label}</span><strong>{x.detail}</strong></div>)}</div></article>
 <article className="panel"><div className="panel-title"><div><h2>Next verification steps</h2><p>Prove or reject the working diagnosis</p></div></div><div className="list"><Link className="list-item row-link" href={`/services/${encodeURIComponent(primary.name)}?environment=${encodeURIComponent(primary.environment)}`}><div><strong>1. Verify user impact</strong><p>Inspect {primary.name} traces, latency and errors</p></div><span>→</span></Link><Link className="list-item row-link" href="/traces"><div><strong>2. Verify dependency path</strong><p>Confirm failed requests traverse {finding.dependency??"the suspected dependency"}</p></div><span>→</span></Link><Link className="list-item row-link" href="/kubernetes"><div><strong>3. Verify infrastructure state</strong><p>Inspect {finding.workload??finding.dependency??"the workload"} replicas, pods, Services and events</p></div><span>→</span></Link><Link className="list-item row-link" href="/incidents"><div><strong>4. Confirm root cause</strong><p>Promote the hypothesis only after responder validation</p></div><span>→</span></Link></div></article></div>
 </>:<article className="panel empty-state"><h2>Not enough telemetry to correlate</h2><p>SignalDeck needs application traces plus supporting Kubernetes or dependency evidence before it can build a useful hypothesis.</p></article>}</>;
}
